### ISSUE TITLE
How to execute XUnit Test Suite?

### ISSUE THREAD

**Issue by agray** [b3b00/coverlet-action#14]
Does Coverlet Action support running XUnit Selenium Test suites?

https://github.com/Sauceforge/Saucery/actions/runs/4713229931/jobs/8359042382

Am I doing something stupid?

Works for NUnit but failing for the XUnit suite.

**Comment by b3b00** [comment]
could you try run
```
run dotnet test -c Debug -p:coverletOutput=opencover.xunit.integration.xml -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude=\"[Merlin.XUnit]Tests.*\" Merlin.XUnit/Merlin.XUnit.csproj
```
and get the output. 
look if a xm output dile us generated

**Comment by b3b00** [comment]
Hello @agray , I 've tried to run tests locally using a free trial account and I get 16 unit tests failing with following message
```
Message d'erreur :
   OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key 'x-ratelimit-remaining' was not present in the dictionary.
  Arborescence des appels de procédure :
  Échoué SupportedRealDevicePlatformTest [792 ms]
```

Do you knwo how I can avoid these to get your unit tests passing an debug coverlet-action ?

Olivier

**Comment by agray** [comment]
I don't see them when I run locally or on saucelabs.  I have a open sauce
account with 5 parallel tests

**Comment by b3b00** [comment]
@agray, have you try to run coverlet locally and check if the output file is correctly generated ?

**Comment by agray** [comment]
I won't have a chance to try your suggestions until next weekend at
the earliest.

Thanks for looking into it.  Hold fire.  I'll let you know.

**Comment by agray** [comment]
I have executed the same command that is failing in GitHub Actions:

`dotnet test -c Debug -p:coverletOutput=opencover.xunit.integration.xml -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude=\"[Merlin.XUnit]Tests.*\" Merlin.XUnit/Merlin.XUnit.csproj`

![image](https://user-images.githubusercontent.com/118102/233759264-fa21b740-876d-4d58-ac82-9d9bd662964c.png)


![image](https://user-images.githubusercontent.com/118102/233759178-522467fe-b51e-43c3-89b7-517035039178.png)


It appears that it did not write the coverletOutput file to disk.

![image](https://user-images.githubusercontent.com/118102/233759358-97d1a9b7-ae83-4167-a43c-9af46bb86137.png)

Which would explain the error I am seeing in GitHub Actions as the subsequent step is looking for this file:

![image](https://user-images.githubusercontent.com/118102/233759467-c83918f8-a635-4054-bace-b7010ebf2901.png)

**Comment by b3b00** [comment]
Hello, thanks for your answer. could you look if you find the output file somewhere else in your repo ? particularly at the root. Maybe convertlet-action does not look for it at the right place.

**Comment by agray** [comment]
Found the problem.  It was my oversight.  I was missing a reference to coverlet.msbuild.
