### ISSUE TITLE
Use Node16 to avoid warning

### ISSUE THREAD

**Issue by agray** [b3b00/coverlet-action#15]
I am currently consuming coverlet v1.2.7

It is emitting the following warning message in GitHub Actions:

`The following actions uses node12 which is deprecated and will be forced to run on node16: b3b00/coverlet-action@1.2.7. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`

**Comment by b3b00** [comment]
Hello @agray , thanks for reporting. Action now uses node 16 with release 1.2.8

**Comment by b3b00** [comment]
Hello @agray , thanks for reporting. Action now uses node 16 with release 1.2.8

**Comment by agray** [comment]
Run is clean

https://github.com/Sauceforge/Saucery/actions/runs/7151581002
