### ISSUE TITLE
More warnings

### ISSUE THREAD

**Issue by agray** [b3b00/coverlet-action#16]
The struggle is real.

![image](https://github.com/b3b00/coverlet-action/assets/118102/5f2c0ac0-d1ac-4253-afdc-979394fa871c)
Hello @agray I ve juste published a 1.2.9 release. Could you try please ?

**Comment by b3b00** [comment]
Hello @agray could you answer please ?

**Comment by b3b00** [comment]
@agray without an answer i'm closing the issue.
