### ISSUE TITLE
Multiple test projects not allowed

### ISSUE THREAD

**Issue by nagesheaton** [b3b00/coverlet-action#18]
I am trying to add multiple test projects to the task but it is throwing that the project doesn't exist. I assume separation will be done through "," between two projects.

Here are the complete logs of the task.
Run b3b00/coverlet-action@1.2.5
  with:
    testProject: Eaton.IoT.Asset/Eaton.IoT.Asset.Service.UnitTest/Eaton.IoT.Asset.Service.UnitTest.csproj,Eaton.IoT.Asset/Eaton.IoT.Asset.UnitTest/Eaton.IoT.Asset.UnitTest.csproj
    output: lcov.info
    outputFormat: lcov
    excludes: [program]*,[test]test.*
    threshold: [8](https://github.com/etn-ccis/cloud-iot-platform-asset-service/actions/runs/8633165234/job/23665556742#step:6:8)0
  env:
    DOTNET_ROOT: C:\Program Files\dotnet
starting...
output : lcov.info
format lcov
UT project Eaton.IoT.Asset/Eaton.IoT.Asset.Service.UnitTest/Eaton.IoT.Asset.Service.UnitTest.csproj,Eaton.IoT.Asset/Eaton.IoT.Asset.UnitTest/Eaton.IoT.Asset.UnitTest.csproj
excludes [program]*,[test]test.*
includes [program]*,[test]test.*
threshold 80
debug 
run dotnet test -c Debug -p:coverletOutput=lcov.info -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:Exclude=\"[program]*,[test]test.*\" Eaton.IoT.Asset/Eaton.IoT.Asset.Service.UnitTest/Eaton.IoT.Asset.Service.UnitTest.csproj,Eaton.IoT.Asset/Eaton.IoT.Asset.UnitTest/Eaton.IoT.Asset.UnitTest.csproj
dotnet failed
Checking threshold 80
MSBUILD : error MSB100[9](https://github.com/etn-ccis/cloud-iot-platform-asset-service/actions/runs/8633165234/job/23665556742#step:6:9): Project file does not exist.
Switch: Eaton.IoT.Asset/Eaton.IoT.Asset.Service.UnitTest/Eaton.IoT.Asset.Service.UnitTest.csproj,Eaton.IoT.Asset/Eaton.IoT.Asset.UnitTest/Eaton.IoT.Asset.UnitTest.csproj

Error: dotnet test failure Command failed: dotnet test -c Debug -p:coverletOutput=lcov.info -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:Exclude=\"[program]*,[test]test.*\" Eaton.IoT.Asset/Eaton.IoT.Asset.Service.UnitTest/Eaton.IoT.Asset.Service.UnitTest.csproj,Eaton.IoT.Asset/Eaton.IoT.Asset.UnitTest/Eaton.IoT.Asset.UnitTest.csproj
Error: error occured : coverage file not found at Eaton.IoT.Asset/Eaton.IoT.Asset.Service.UnitTest/Eaton.IoT.Asset.Service.UnitTest.csproj,Eaton.IoT.Asset/Eaton.IoT.Asset.UnitTest/lcov.info
coverlet test done.

![image](https://github.com/b3b00/coverlet-action/assets/107124679/4b8754a1-3cde-411c-9107-98ec70554efb)

![image](https://github.com/b3b00/coverlet-action/assets/107124679/275dfdd8-5b02-4fa7-adc6-54b90b0c79da)

Kindly help..!

**Comment by olduh29** [comment]
Hello @nagesheaton , this actions does not allow many unit test project.

**Comment by nagesheaton** [comment]
While running on Solution level I am getting two different reports.
![image](https://github.com/b3b00/coverlet-action/assets/107124679/a2b3edbd-4731-4cb7-8a7d-652db8f634ac)

![image](https://github.com/b3b00/coverlet-action/assets/107124679/8ee93c36-603c-48df-901e-e986f485d7fb)

Is there any way to get consolidated test report?

**Comment by nagesheaton** [comment]
Also while running the Unittest in Visual Studio I am getting 90+ Coverage but <80 in this command.
![image](https://github.com/b3b00/coverlet-action/assets/107124679/09544a0c-ec4b-4485-99ad-7facbeb45e7f)

Is there any specific reason? Or I have to add anything here explicitly ? Since I am able to see the projects covered in both of the cases is different.

If you see the report in Visual Studio it covers different Projects.
![image](https://github.com/b3b00/coverlet-action/assets/107124679/bb21afea-c69e-47d1-b578-8847c73a2135)

But some projects are missing in the coverlet command.

**Comment by b3b00** [comment]
Maybe you have to exclude some projects from code coverage. Coverlet-action is only a gh action to use coverlet so for coverage report issue you should better look at how to use coverlet

**Comment by nagesheaton** [comment]
Thanks for the help. I will check and update here by Tomorrow.

**Comment by olduh29** [comment]
@nagesheaton , could you share if you find a reason for coverage difference ? and if so what was the issue ? it could help future users.
