### ISSUE TITLE
@Question

### ISSUE THREAD

**Issue by Korgath** [b3b00/coverlet-action#3]
What License are you publishing this under - MIT, Apache or something else?

**Comment by b3b00** [comment]
Hello @Korgath , I'v just added the MIT license. Thanks for pointing this.
Are you planning to use this GH action for a project ? Would you mind share if it fits your need or if you would need some changes ?

**Comment by Korgath** [comment]
Hi @b3b00 ,
Thanks for clarifying so quickly.
At the moment I am trying different approaches how to best implement code coverage with coverlet. I'll get back to you how this fits in.
