### ISSUE TITLE
Version 1.1.9 appears to have broken output

### ISSUE THREAD

**Issue by agray** [b3b00/coverlet-action#8]
Just upgraded from 1.1.7 to 1.1.9 in my [pipeline](https://github.com/Sauceforge/Saucery/runs/5255589150?check_suite_focus=true)

It seems like the log output is broken when compared to the ouput on the previous [run](https://github.com/Sauceforge/Saucery/runs/5255561009?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/118102/154780342-3e18dd70-8f43-485c-a4c8-d7065b1c3ce0.png)

**Comment by agray** [comment]
Issue is not present in release 1.1.8.

https://github.com/Sauceforge/Saucery/runs/5255716476?check_suite_focus=true

**Comment by b3b00** [comment]
Hello @agray , I've just published a new version 1.2.0 which fix it. The issue appeared when fixing #7

**Comment by b3b00** [comment]
hello @agray I've just published v1.2.2 that clean output a bit. Should works fine now. please keep me informed !

**Comment by agray** [comment]
Thanks.  v1.2.2 looks to be working a-ok.
